DROP TABLE IF EXISTS SUBSCRIPTION;
CREATE TABLE SUBSCRIPTION(id INT AUTO_INCREMENT PRIMARY KEY, quotation_id INT, start_date DATE, valid_until DATE);
DROP TABLE IF EXISTS QUOTATION;
CREATE TABLE QUOTATION(id INT AUTO_INCREMENT PRIMARY KEY, beginning_of_insurance DATE, customer_id INT, date_of_signing_mortgage DATE, insured_amount INT);
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(id INT AUTO_INCREMENT PRIMARY KEY, birth_date DATE, email VARCHAR(255), first_name VARCHAR(255), last_name VARCHAR(255), middle_name VARCHAR(255), phone_number VARCHAR(255));